name: Publish Docker image

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - main
env:
  REGION_ID: cn-beijing
  REGISTRY: registry.cn-beijing.aliyuncs.com
  NAMESPACE: oneflow

concurrency:
  group: sf-next-chat-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: github.repository_owner == 'siliconflow'
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to ACR with the AccessKey pair
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.${{env.REGION_ID}}.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            NEXT_PUBLIC_SF_NEXT_CHAT_CLIENT_ID=${{ vars.NEXT_PUBLIC_SF_NEXT_CHAT_CLIENT_ID }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/next-chat-sf
            oneflowinc/silicon-chat:latest
            oneflowinc/silicon-chat:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
            
